In [1]:
from data_ingestion import *
from data_processing import *
import json
from typing import Dict, Any
import numpy as np
import pandas as pd
import openpyxl

In [3]:
# !pip install langchain
# !pip install chromadb

In [2]:
df = pd.read_excel('/Users/ruhwang/Desktop/AI/spring2025_courses/capstone/RagSheets/example_sheets/Detailed_Expense_Breakdown.xlsx')

In [8]:
# df.head(25)

In [3]:
# Identify the row index where the first numeric year appears
year_row_index = None
for i in range(len(df)):
    non_null_values = df.iloc[i].dropna()
    if non_null_values.astype(str).str.match(r'^\d{4}(\.0)?$').all():  # Matches years like 2024 and 2024.0
        year_row_index = i
        break

if year_row_index is None:
    raise ValueError("No year row found in the dataset.")

# Extract column names from the identified row (convert floats to int for clean column names)
new_columns = df.iloc[year_row_index+1].values.astype(str).tolist()
# new_columns = [col if not col.replace('.0', '').isdigit() else str(int(float(col))) for col in new_columns]
new_columns[0] = 'Category'
new_columns = [col if not col.replace('.0', '').isdigit() else str(int(float(col))) for col in new_columns]
# new_columns

In [ ]:
def clean_dataframe(df):
    """
    Cleans a dataframe by:
    1. Identifying the row that contains year values (both integer and float).
    2. Renaming columns using the detected years.
    3. Removing metadata rows above the detected year row.
    4. Ensuring all columns have valid names.
    5. Filling NaN values with -inf.
    
    Parameters:
    df (pd.DataFrame): Raw dataframe with metadata and financial data.
    
    Returns:
    pd.DataFrame: Processed dataframe with correct column names and missing values replaced.
    """
    
    # Identify the row index where the first numeric year appears
    year_row_index = None
    for i in range(len(df)):
        non_null_values = df.iloc[i].dropna()
        if non_null_values.astype(str).str.match(r'^\d{4}(\.0)?$').all():  # Matches years like 2024 and 2024.0
            year_row_index = i
            break

    if year_row_index is None:
        raise ValueError("No year row found in the dataset.")

    # Extract column names from the identified row (convert floats to int for clean column names)
    new_columns = df.iloc[year_row_index+1].values.astype(str).tolist()
    new_columns = [col if not col.replace('.0', '').isdigit() else str(int(float(col))) for col in new_columns]

    # Ensure the first column has a proper name (e.g., "Category")
    new_columns[0] = "category"

    # Remove metadata rows above the detected year row and reset index
    df = df.iloc[year_row_index+2:,]

    # Assign new column names
    df.columns = new_columns # 

    # Fill NaN values with -inf
    df = df.fillna(-np.inf).reset_index(drop=True, inplace=False)
    df.set_index('category', inplace=True)
    
    return df

In [5]:
clean = clean_dataframe(df)
clean.head()

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
category,,,,,,,,,,,,,
Expense,245432.40,250345.09,268374.95,277593.25,278855.13,277902.16,286654.95,292042.74,294231.14,318675.11,351185.68,389392.489,402020.93
Compensation of employees,78218.52,80926.64,81930.41,82983.93,84175.48,79645.84,86199.00,87921.00,91891.09,93065.72,101772.86,102368.290,121039.41
Wages and salaries,67551.09,69871.69,70547.89,71265.23,72341.38,68489.42,74083.26,75440.89,78989.26,80201.80,87695.27,88171.210,104683.11
Employers' social contributions,10667.43,11054.95,11382.52,11718.70,11834.10,11156.42,12115.74,12480.11,12901.83,12863.92,14077.59,14197.080,16356.30
Use of goods and services,26682.58,26673.55,32022.52,24249.71,28226.90,31866.26,32365.45,33011.10,35431.14,35396.34,41297.10,46173.170,51002.80

In [6]:
clean.to_csv("./clean.csv")

#### START HERE

In [7]:
from data_ingestion import *
from data_processing import *
import json
from typing import Dict, Any
import numpy as np
import pandas as pd
import openpyxl

In [8]:
clean = pd.read_csv("./clean.csv")

In [9]:
def extract_vals_from_df(df, col, year):
    return float(df.loc[col, year])

In [12]:
clean.head()

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
category,,,,,,,,,,,,,
Expense,245432.40,250345.09,268374.95,277593.25,278855.13,277902.16,286654.95,292042.74,294231.14,318675.11,351185.68,389392.489,402020.93
Compensation of employees,78218.52,80926.64,81930.41,82983.93,84175.48,79645.84,86199.00,87921.00,91891.09,93065.72,101772.86,102368.290,121039.41
Wages and salaries,67551.09,69871.69,70547.89,71265.23,72341.38,68489.42,74083.26,75440.89,78989.26,80201.80,87695.27,88171.210,104683.11
Employers' social contributions,10667.43,11054.95,11382.52,11718.70,11834.10,11156.42,12115.74,12480.11,12901.83,12863.92,14077.59,14197.080,16356.30
Use of goods and services,26682.58,26673.55,32022.52,24249.71,28226.90,31866.26,32365.45,33011.10,35431.14,35396.34,41297.10,46173.170,51002.80

In [13]:
extract_vals_from_df(clean, 'Expense', '2022')

389392.489

5 years of expense (ie. "Wages and salaries" + "Private")

json_total = {
    JSON_1: 
    {
        "function": "2017",
        "Wages and salaries": "2017",
        "Private": "2017"
    }

    JSON_2: 
    {
        "function": "2018",
        "Wages and salaries": "2018",
        "Private": "2018"
    }
    ....
    }

In [ ]:
from llama_index.core.tools import FunctionTool, ToolMetadata
from llama_index.core.agent import ReActAgent
from llama_index.core import VectorStoreIndex, ServiceContext, SimpleDirectoryReader, PromptTemplate, get_response_synthesizer

LLM will return:

```JSON file

{

"name of funtion" : "addition",

"Expense"         : "2022", 

"Capital"         : "2022"

}

In [485]:
clean["2011"]

category
Expense                                     245432.40
Compensation of employees                    78218.52
Wages and salaries                           67551.09
Employers' social contributions              10667.43
Use of goods and services                    26682.58
Consumption of fixed capital                     -inf
Interest expense                             41107.57
To nonresidents                               6854.75
To residents other than government units     34052.62
To other government units                      200.20
Subsidies                                     2528.50
To public corporations                         679.61
To private enterprises                        1848.89
To other sectors                                 0.00
Grants                                       84308.14
To foreign governments                          48.07
To international organizations                1012.10
To other government units                    83247.97
Current                                      76308.10
Capital                                       6939.87
Social benefits                               3747.21
Social security benefits                         0.00
Social assistance benefits                    3744.30
Employment-related social benefits               2.94
Other expense                                 8839.88
Property expense other than interest             0.00
Expense on other transfers                    8839.88
Name: 2011, dtype: float64

In [15]:
import json
from typing import Dict, Any, Callable, List, Union


def execute_function(json_data: str, df: pd.DataFrame) -> Any:
    """
    Parses a JSON input, retrieves data from a DataFrame based on year and
    field, dispatches the call to the appropriate function, and returns
    the result.

    Args:
        json_data: The JSON string containing a SINGLE function call and args.
        df: The Pandas DataFrame containing the financial data.

    Returns:
        The result of the function call, or an error string.
    """
    try:
        data = json.loads(json_data)
        if isinstance(data, list):
            return "Error: Only one function call per JSON input is allowed."
    except json.JSONDecodeError:
        return "Error: Invalid JSON format."

    function_name = data.get("function")
    if not function_name:
        return "Error: 'function' key missing in JSON."

    function_map: Dict[str, Callable] = {
        "addition": add,
        "subtraction": subtract,
        "division": divide,
        "multiplication": multiply,
        "percentage": return_percentage,
        # Add more functions as needed
    }

    function = function_map.get(function_name)
    if not function:
        return f"Error: Function '{function_name}' not found."

    args = {}
    errors = []

    # Dynamically extract arguments and retrieve data from json data
    for arg_name, year_str in data.items():
        if arg_name == "function":
            continue

        if not isinstance(year_str, str):
            errors.append(f"Error: Year for argument '{arg_name}' must be a string.")
            continue

        try:
            # Use extract_vals_from_df to get data from DataFrame
            value = extract_vals_from_df(df, arg_name, year_str)
            args[arg_name] = value  # No need to cast to float *here*
        except (KeyError, TypeError) as e:  # Handle DataFrame access errors
            errors.append(f"Error retrieving data for '{arg_name}' ({year_str}): {e}")
            continue
        except ValueError as e:
            errors.append(f"ValueError for argument {arg_name}: {e}")
            continue

    if errors:
        return "\n".join(errors)

    # Call function with retrieved arguments.
    try:
        result = function(*args.values()) # incorrect: tuple(args.values()) or args[a] for a in args.keys()
        return result # output
    except TypeError as e:
        return f"Error calling function '{function_name}': {e}"
    except Exception as e:
        return f"Error during {function_name}: {e}"

In [10]:
extract_vals_from_df(clean, "Capital", "2022"), extract_vals_from_df(clean, "Current", "2022")

(9520.7, 140375.8)

### Demo without LLM Output

JSON —> python function (take info from the JSON, manipulate the info, and then give the output) —> answer

In [ ]:
# --- Test Cases ---
# Create a sample DataFrame for testing
data = {
    "2023": {"Expense": 100.0, "Capital": 500.0, "Revenue": 1000.0, "Debt": 200.0},
    "2024": {"Expense": 120.0, "Capital": 600.0, "Revenue": 1100.0, "Debt": 250.0},
}
df = pd.DataFrame.from_dict(data, orient='index')
df = df.transpose()  # Now columns are years, rows are fields

In [12]:
json_input_1 = """
{
    "function": "addition",
    "Debt": "2023",
    "Capital": "2023"
}
"""
ans = execute_function(json_input_1, df)
print(f"Test 1: {ans}")

Test 1: 700.0

In [13]:
json_data = json.loads(json_input_1)
json_data

{'function': 'addition', 'Debt': '2023', 'Capital': '2023'}

### Demo With LLM Output

In [16]:
#Import LLM

from llama_index.core.indices import VectorStoreIndex
from llama_index.llms.cohere import Cohere
from llama_index.core.llms import ChatMessage
from llama_index.core import PromptTemplate

In [17]:
import os
from dotenv import load_dotenv

load_dotenv()

# Load the Cohere API key from the environment variable
cohere_api = os.getenv("COHERE_API_KEY")

# Initialize the Cohere model
cohere_model = Cohere(
    api_key=cohere_api, model="command-r-plus" # "command-r-08-2024"
)

# Create a chat message
# message = ChatMessage(role="user", content="What is 2 + 3?")

# Get the response from the Cohere model
# response = cohere_model.chat([message])
# print(response)

In [18]:
from llama_index.core.base.llms.types import ChatMessage, MessageRole
from llama_index.core.prompts.base import ChatPromptTemplate

In [19]:
symtem_prompt= ChatMessage(
    content=(
        "You are a financial expert Q&A system trusted for various tasks.\n"
        "Always answer the query using the provided context information, "
        "and not prior knowledge.\n"
        "Some rules to follow:\n"
        "1. Ensure top priorities in relevance and accuracy for generating answers.\n"
        "2. Avoid statements like 'Based on the context, ...' or "
        "'The context information ...' or anything along those lines"
    ),
    role=MessageRole.SYSTEM,
)

qa_template_str = content=( 
    # [ChatMessage(   , role=MessageRole.USER,) ]
    "You are a  expert that can answer users' queries and perform calculations.\n"
    # "Context information is below. \n"
    # "---------------------\n"
    # "{context_str}"
    # "\n---------------------\n"
    "Given the context information and not prior knowledge, "
    "retrieve the relevant year(s), field_1, and field_2 from {query_str}\n"
    "Output your response in JSON format, using the following structure:\n"
    "```json\n"
    "{{\n"
    '  "function": "name_of_function",\n'
    '  "field_1": "year",\n'
    '  "field_2": "year",\n'
    "   ...\n"
    "}}\n"
    "```\n"
    "Available functions for name_of_function: addition, subtraction, division, multiplication, percentage.\n"
     "ONLY return the JSON and nothing else."
    )

qa_template = PromptTemplate(qa_template_str)

In [20]:
from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    PromptTemplate,
    ServiceContext,
    get_response_synthesizer
)

In [21]:
from llama_index.core import ServiceContext, set_global_service_context, Settings
import cohere

In [22]:
Settings.llm = cohere_model
# Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")
# Settings.node_parser = SentenceSplitter(chunk_size=512, chunk_overlap=20)
Settings.num_output = 512
Settings.context_window = 4000

In [23]:
preamble = """ 
    You are a financial expert Q&A system trusted for various tasks.
    Always answer the query and not prior knowledge.
    Output your response in JSON format, using the following structure:
    ```json\n
    {{\n
        "function": "name_of_function",\n
        "field_1": "year",\n
        "field_2": "year",\n
    "   ...\n"
    }}\n
    ```\n

    Available functions for name_of_function: addition, subtraction, division, multiplication, percentage.
    ONLY return the JSON and nothing else. If necessary, break operations down to several steps and output
    multiple json outputs. 
    
    Some rules to follow:
    1. Ensure top priorities in relevance and accuracy for generating answers.
    2. Avoid statements like 'Based on the context, ...' or 'The context information ...' or anything along those lines
"""

In [24]:
cohere_api = os.getenv("COHERE_API_KEY")
ch = cohere.ClientV2(api_key="7D5Y30Vg7BYjfZk1huZ5AAZ58esXEr0jH2QpWFa8")

In [ ]:
# query = "What is the total expenses and capital of 2023"

# # get model response
# response = ch.chat(
#   model="command-r-08-2024",
#   messages=[{"role" : "system", "content" : preamble},
#             {"role" : "user", "content" : query}],
#   # documents=documents,
#   temperature=0.1
# )

# print("Final answer:")
# print(response.message.content[0].text)

Final answer:

```json
{
  "function": "addition",
  "expenses": 2023,
  "capital": 2023
}
```

NOTE:

We can then pass the final answer into the execute_function() as previously defined.

In [92]:
import jsonschema

In [ ]:
classify_response_schema = {
    "type": "object",
    "properties": {
        "task_type": {
            "type": "string",
            "enum": ["retrieve_numbers", "give_advice", "perform_calculations"] # , "combined"
        },
        "description": {"type": "string"},
        "plan": {"type": "array", "items": {"type": "string"}}
    },
    "required": ["task_type"],
     "oneOf": [
        {"required": ["task_type", "description"], "properties": {"task_type": {"const": "retrieve_numbers"}}},
        {"required": ["task_type", "description"], "properties": {"task_type": {"const": "give_advice"}}},
        {"required": ["task_type", "plan"], "properties": {"task_type":{"const": "perform_calculations"}}},
        {"required": ["task_type"], "properties": {"task_type": {"const": "combined"}}}
    ]
}

Categorize Tasks into Different Categories

In [116]:
clean.index

Index(['Expense', 'Compensation of employees', 'Wages and salaries',
       'Employers' social contributions', 'Use of goods and services',
       'Consumption of fixed capital', 'Interest expense', 'To nonresidents',
       'To residents other than government units', 'To other government units',
       'Subsidies', 'To public corporations', 'To private enterprises',
       'To other sectors', 'Grants', 'To foreign governments',
       'To international organizations', 'To other government units',
       'Current', 'Capital', 'Social benefits', 'Social security benefits',
       'Social assistance benefits', 'Employment-related social benefits',
       'Other expense', 'Property expense other than interest',
       'Expense on other transfers'],
      dtype='object', name='category')

#### Classification Template

In [333]:
classification_template = """
Generate a JSON containing primary task type from your analysis of the user's query. 

Task Types:
  - retrieve_numbers
  - give_advice
  - perform_calculations
  - other

If the task is "retrieve_numbers", return "items" (a list of strings) representing what to retrieve.
If the task is "give_advice", return "description" (string) describing what the user wants to advice on. 
If the task is "perform_calculations", return "plan" (json object) containing high level steps to perform the necessary calculations.
Output the plan as a JSON object with key "steps". The value of "steps" should be an array of strings.

Ensure not to confuse calculations with retrieval for certain words like 'ratio', 'total', 'sum', 'net',
'percentage', 'per', 'rate', 'cumulative', 'combined', 'difference', 'overall', 'growth', 'change', which are calculations.
Be sure to translate them into "add", "subtract", "multiply", and "divide" operations. For example, "add ['step2, step3']" means add the results of step2 and step3.

NOTE: the user query may not contain the correct year or field name. 
Be sure to identify the right field from {available_fields} and year from {available_years}.

(Example 1):
User Query: What was the revenue and capital in 2023?
Output:
{{
  "task_type": "retrieve_numbers",
  "items": ["revenue, 2023", "capital, 2023"]
}}

(Example 2):
User Query: Give me advice on improving my company's financial performance for investors?
Output:
{{
    "task_type": "give_advice",
    "description": "evaluate company's financial performance for investors" 
}}

(Example 3):
User Query: What percentage of 2022 expenses paid to employee wages?
Output:
{{
    "task_type": "perform_calculations",
    "plan": {{
        "step1": "retrieve ['Expense, 2022']",
        "step2: "retrieve ['Expense, 2022']",
        "step3": "divide ['step1, step2']"
        "step4": "multiply ['step3, 100']"
    }}
}}
"""

In [ ]:
from llama_index.core.prompts import PromptTemplate

brief_classification_template = PromptTemplate("""
You are an AI classifier. Given a user query and structured data, classify the task into one of:
- retrieve_numbers
- give_advice
- perform_calculations
- other

Ensure to identify the right field from {{ available_fields }} and year from {{ available_years }}.

Respond in JSON matching this schema:
{
  "task_type": "...",
  "description": "...",
  "items": ["..."],
  "plan": ["step1: ...", "step2: ..."], ...}
}

Query: {{ query }}
Available Fields: {{ available_fields }}
Available Years: {{ available_years }}
""")

In [ ]:
advice_template = PromptTemplate("""
You are a financial advisor. Given a user query string {{ query }} and description {{ description }}, 
generate an advice in a concise and clear manner. Refer to {{ table }} for any necessary data.                           
Ensure to identify the right field from {{ available_fields }} and year from {{ available_years }}.                            
                                      
If an advice is not possible without analyzing historical data trends, break down the needed steps in a JSON format.
                                 
(ie). How can I reduce my company's expenses for next year? 
{{
    "task_type": "perform_calculations",
    "plan": {{
        "step1": "find all relevant fields related to expenses for all years",
        "step2: "determine which ones are fixed and which ones are variable",
        "step3": "analyze the trends of each field"
        "step4": "tell the user what to do to reduce spending for each category"
    }}
}}
""")

In [ ]:
from llama_index.llm_predictor import LLMPredictor
from llama_index.query_engine import RetrieverQueryEngine

# === Setup LLM and Prompt ===
llm = OpenAI(temperature=0)
llm_predictor = LLMPredictor(llm=llm)

prompt_template = PromptTemplate(
    """
    You are a financial advisor. Given a user query string {{ query }} and description {{ description }}, 
    generate an advice in a concise and clear manner. Refer to the provided table below for any necessary data.                           
    Ensure to identify the right field from {{ available_fields }} and year from {{ available_years }}.                            

    Table:
    {{ table }}

    If an advice is not possible without analyzing historical data trends, break down the needed steps in a JSON format.
    """
)

# === Load and index documents ===
def build_retriever_from_docs(directory_path: str) -> RetrieverQueryEngine:
    documents = SimpleDirectoryReader(directory_path).load_data()
    index = VectorStoreIndex.from_documents(documents)
    return index.as_query_engine()

# === Advice generation + execution ===
def generate_or_execute_advice(query: str, description: str, df: pd.DataFrame, retriever_engine: RetrieverQueryEngine) -> Any:
    available_fields = df.columns.tolist()
    available_years = [col for col in df.columns if any(str(y) in str(col) for y in range(2000, 2030))]
    table_str = df.to_string()

    context_docs = retriever_engine.query(query)
    context_text = str(context_docs)

    final_prompt = prompt_template.format(
        query=query,
        description=description,
        table=table_str,
        available_fields=available_fields,
        available_years=available_years,
    ) + f"\n\nAdditional context:\n{context_text}"

    response = llm_predictor.predict(prompt=PromptTemplate(final_prompt))

    try:
        structured = json.loads(response)
        if structured.get("task_type") == "perform_calculations":
            return execute_plan(structured["plan"], df)
        else:
            return response
    except Exception:
        return response

def execute_plan(plan: Dict[str, str], df: pd.DataFrame):
    steps_output = {}
    for step, description in plan.items():
        steps_output[step] = f"[TODO] Implement: {description}"
    return steps_output

In [328]:
def classify_step(ch, query: str, df: pd.DataFrame = clean, template: PromptTemplate = classification_template) -> str:
  prompt = template.format(
    query=query,
    available_fields=", ".join(clean.index),
    available_years=", ".join(clean.columns),
  )
  response = ch.chat(model="command-r-08-2024", messages=[{"role": "user", "content": prompt}], temperature=0.1)
  return response.message.content[0].text

In [334]:
output0 = classify_step(ch, query="what percentage of expense was spent on wages in 2022?", df=clean, template=classification_template)

In [335]:
output0

'{\n    "task_type": "perform_calculations",\n    "plan": {\n        "step1": "retrieve [\'Wages and salaries, 2022\']",\n        "step2": "retrieve [\'Compensation of employees, 2022\']",\n        "step3": "add [\'step1, step2\']",\n        "step4": "retrieve [\'Expense, 2022\']",\n        "step5": "divide [\'step3, step4\']",\n        "step6": "multiply [\'step5, 100\']"\n    }\n}'

This function is only for EXPERIMENTING!

In [ ]:
def get_llm_answer(query: str, model: str="command-r-08-2024", template: str=classification_template) -> str:
    # get model response
    response = ch.chat(
        model=model,
        messages=[{"role" : "system", "content" : template},
                    {"role" : "user", "content" : query}],
        # documents=documents,
        # return a json file type
        response_format={
            "type": "json_object",
            "schema": {
                "type": "object",
                "properties": {
                    "task_type": {"type": "string"},
                    "description": {"type": "string"},
                    "plan": {"type": "array"}
                },
                "required": ["task_type"],
            },
        },
            # make it completely deterministic for easy testing
        temperature=0 
    )

    answer = response.message.content[0].text #.text is required
    print("Final answer:")
    print(answer)
    return answer

In [191]:
from llama_index.core.program import LLMTextCompletionProgram

class ClassificationPlan(BaseModel):
    task_type: Literal["retrieve_numbers", "give_advice", "perform_calculations", "other"]
    description: Optional[str] = None
    items: Optional[List[str]] = None
    plan: Optional[List[str]] = None

program = LLMTextCompletionProgram.from_defaults(
    output_cls=ClassificationPlan,
    prompt_template_str=brief_classification_template,
    verbose=True,
)

In [ ]:
output = program(query="what was the Expense in 2021?", available_fields=clean.index, available_years=clean.columns)
output

ClassificationPlan(task_type='retrieve_numbers', description=None, items=["How many unique values are there for the field 'available_fields'?", "What is the range of years available in 'available_years'?"], plan=None)

In [190]:
new = program(query="calculate the ratio of Wages and salaries to Expense in 2021?", available_fields=clean.index, available_years=clean.columns)
new

ClassificationPlan(task_type='retrieve_numbers', description=None, items=["How many unique values are there for 'available_fields'?", "What is the range of years in 'available_years'?"], plan=None)

Not for now:

In [ ]:
"""(Example 3):
User Query: What percentage of 2022 expenses did employee wages account for?
Output:
{{
    "task_type": "perform_calculations",
    "steps":{{"function": "division", // One of: addition, subtraction, division, multiplication, percentage, retrieval
    "year": "2022",                   // The year as a string
    "field1": "Wages and salaries",   // The name of the first field
    "field2": "Expenses"}}            // The name of the second field (only if needed)
}}

(Example 3):
User Query: What percentage of 2022 expenses did employee wages account for?
Output:
{{
    "task_type": "perform_calculations",
    "plan": {{
        "steps": [
            {{"function": "division", "field1": "Wages and salaries", "field2": "Expenses", "year": "2022", "output": "0"}},
            {{"function": "percentage", "field1": "output"}}
        ]
    }}
}}
"""

Output Schema

Classification step

In [413]:
from pydantic import BaseModel, Field
from typing import List, Literal, Optional

# classification object schema
class ClassificationPlan(BaseModel):
    task_type: Literal["retrieve_numbers", "give_advice", "perform_calculations", "other"]
    description: Optional[str] = None
    items: Optional[List[str]] = None
    plan: Optional[Dict[str, str]] = None

Structure parser for JSON

In [421]:
cohere_model

Cohere(callback_manager=<llama_index.core.callbacks.base.CallbackManager object at 0x16c777dd0>, system_prompt=None, messages_to_prompt=<function messages_to_prompt at 0x12fa5a2a0>, completion_to_prompt=<function default_completion_to_prompt at 0x12fc1d440>, output_parser=None, pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'>, query_wrapper_prompt=None, model='command-r-plus', temperature=None, max_retries=10, additional_kwargs={}, max_tokens=8192)

In [429]:
from llama_index.core.query_pipeline import CustomQueryComponent
from llama_index.core.llms import ChatMessage
from llama_index.core.llms import MessageRole
from llama_index.core.prompts import PromptTemplate

from pydantic import PrivateAttr

# cohere_model = Cohere(
#     api_key=cohere_api, model="command-r-plus-08-2024"# "command-a-03-2025"
# )

class StructuredParserComponent(CustomQueryComponent):
    _prompt_template: PromptTemplate = PrivateAttr()
    _schema_class: type[BaseModel] = PrivateAttr()
    _llm: Cohere = PrivateAttr()

    def __init__(
        self,
        prompt_template: PromptTemplate,
        schema: type[BaseModel],
        llm: Cohere = cohere_model,
        api_key: str = cohere_api,
    ):
        super().__init__()
        self._prompt_template = prompt_template
        self._schema_class = schema
        self._llm = llm

    def _run_component(self, **kwargs):
        prompt = self._prompt_template.format(**kwargs)
        messages = [ChatMessage(role=MessageRole.USER, content=prompt)]
        
        response = self._llm.chat(messages=messages, temperature=0.1)
        parsed = self._schema_class.model_validate_json(response.message.content)
        return {"parsed_output": parsed}

    @property
    def _input_keys(self): 
        return {"query_str", "available_fields", "available_years"}

    @property
    def _output_keys(self): 
        return {"parsed_output"}

Apply different treatment for task types after JSON parsing

In [ ]:
test = ["Expense, 2022", "Capital, 2022"]
parsed = {}
parsed["items"] = test

result = {
    item: float(clean.loc[item.split(",")[0].strip(), item.split(",")[1].strip()])
    if item.split(",")[0].strip() in clean.index else None
    for item in parsed["items"]
}

In [205]:
result

{'Expense, 2022': 389392.489, 'Capital, 2022': 9520.7}

Pipeline

In [498]:
# Initialize with command-r-08-2024
cohere_model = Cohere(
    model="command-r-08-2024",
    api_key=cohere_api,  # Make sure to use a valid API key
    temperature=0.1,
    max_tokens=2000
)

In [500]:
clean.head()

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
category,,,,,,,,,,,,,
Expense,245432.40,250345.09,268374.95,277593.25,278855.13,277902.16,286654.95,292042.74,294231.14,318675.11,351185.68,389392.489,402020.93
Compensation of employees,78218.52,80926.64,81930.41,82983.93,84175.48,79645.84,86199.00,87921.00,91891.09,93065.72,101772.86,102368.290,121039.41
Wages and salaries,67551.09,69871.69,70547.89,71265.23,72341.38,68489.42,74083.26,75440.89,78989.26,80201.80,87695.27,88171.210,104683.11
Employers' social contributions,10667.43,11054.95,11382.52,11718.70,11834.10,11156.42,12115.74,12480.11,12901.83,12863.92,14077.59,14197.080,16356.30
Use of goods and services,26682.58,26673.55,32022.52,24249.71,28226.90,31866.26,32365.45,33011.10,35431.14,35396.34,41297.10,46173.170,51002.80

In [ ]:
from llama_index.core.query_pipeline import QueryPipeline, CustomQueryComponent
from llama_index.core.llms import ChatMessage, MessageRole
from llama_index.llms.cohere import Cohere
from llama_index.core.prompts import PromptTemplate
from pydantic import PrivateAttr

import pandas as pd
import json
import re

# -- Arithmetic Functions --
add = lambda a, b: a + b
multiply = lambda a, b: a * b
subtract = lambda a, b: a - b
divide = lambda a, b: a / b if (a is not None and b not in [0, None]) else None
return_percentage = lambda a, b: (a / b) * 100 if (a is not None and b not in [0, None]) else None

# -- Helper Functions --
def extract_vals_from_df(df, col, year):
    return float(df.loc[col, year]) if col in df.index and year in df.columns else None

def retrieving(df, items):
    answer = []
    if len(items) == 2:
        col, year = items[0].strip(), items[1].strip()
        answer.append(extract_vals_from_df(df, col, year))
    else:
        answer.append(None)
    return answer

# -- Plan Execution Logic --
# -- Plan Execution Logic --
def executing_plan_from_json(df, json_str):
    try:
        parsed = json.loads(json_str)
        print("🔨 Parsed JSON:", parsed)  # Debug
        plan = parsed.get("plan", {})
        context = {}

        for step_name in sorted(plan.keys()):
            instruction = plan[step_name].strip()
            lowered = instruction.lower()
            pattern = r"'(.*?)'|\"(.*?)\""
            matches = re.findall(pattern, instruction)[0][0] if re.findall(pattern, instruction) else None
            matches = [m.strip() for m in matches.split(",")] if matches else []

            if lowered.startswith("retrieve"):
                values = retrieving(df, matches)
                context[step_name] = values[0] if len(values) == 1 else values
            else:
                resolved_vals = []
                for arg in matches:
                    if arg.startswith("step"):
                        val = context.get(arg)
                        if val is None:
                            try:
                                val = float(arg)
                            except ValueError:
                                val = None
                        resolved_vals.append(val)

                if lowered.startswith("add") and len(resolved_vals) >= 2:
                    context[step_name] = add(resolved_vals[0], resolved_vals[1])
                elif lowered.startswith("subtract") and len(resolved_vals) >= 2:
                    context[step_name] = subtract(resolved_vals[0], resolved_vals[1])
                elif lowered.startswith("divide") and len(resolved_vals) >= 2:
                    context[step_name] = divide(resolved_vals[0], resolved_vals[1])
                elif lowered.startswith("multiply") and len(resolved_vals) >= 2:
                    context[step_name] = multiply(resolved_vals[0], resolved_vals[1])
                elif lowered.startswith("percentage") and len(resolved_vals) >= 2:
                    context[step_name] = return_percentage(resolved_vals[0], resolved_vals[1])
                else:
                    context[step_name] = None

        return context  # Return the context with computed values, not the plan
    
    except Exception as e:
        print("❌ JSON parsing failed:", e)
        raise

# -- Components --
class ExecutePlanComponent(CustomQueryComponent):
    _df: pd.DataFrame = PrivateAttr()

    def __init__(self, df):
        super().__init__()
        self._df = df

    def _run_component(self, **kwargs):
        print("⚡ ExecutePlanComponent received:", kwargs)  # Debug input
        try:
            result = executing_plan_from_json(self._df, kwargs["json_str"])
            print("✅ Execution result:", result)
            return {"executed_plan": result}
        except Exception as e:
            print("❌ Execution failed:", str(e))
            raise

    @property
    def _input_keys(self): return {"json_str"}
    @property
    def _output_keys(self): return {"executed_plan"}

class ClassifyStepComponent(CustomQueryComponent):
    _llm: Cohere = PrivateAttr()
    _template: PromptTemplate = PrivateAttr()
    _df: pd.DataFrame = PrivateAttr()

    def __init__(self, cohere_model, template: PromptTemplate, df: pd.DataFrame):
        super().__init__()
        self._llm = cohere_model
        self._template = template
        self._df = df

    def _run_component(self, **kwargs):
        # 1. Format the prompt with safe string conversion
        formatted_prompt = self._template.format(
            query=kwargs["query_str"],
            available_fields=", ".join(str(field) for field in self._df.index),
            available_years=", ".join(str(year) for year in self._df.columns)
        )
        
        # 2. Prepare messages (use lowercase role)
        messages = [
            ChatMessage(role=MessageRole.USER, content=formatted_prompt)  # Changed to use ChatMessage
        ]
        
        # 3. Get response from command-r
        response = self._llm.chat(
            messages=messages,
            response_format={"type": "json_object"},
            temperature=0.1
        )
        
        # 4. Process response (command-r has different response structure)
        try:
            content = response.message.content
            if isinstance(content, list):
                content = content[0].text if hasattr(content[0], 'text') else str(content[0])
            
            # Ensure valid JSON
            parsed = json.loads(content)
            print("📥 Raw LLM output:\n", parsed)
            
            # Transform if needed (same as before)
            if "plan" not in parsed:
                if "items" in parsed:
                    parsed = {
                        "plan": {
                            f"step{i+1}": f"Retrieve '{item.split(',')[0].strip()}', '{item.split(',')[1].strip()}'"
                            for i, item in enumerate(parsed["items"])
                        }
                    }
            
            return {"json_str": json.dumps(parsed)}
            
        except Exception as e:
            raise ValueError(f"Failed to process LLM response: {str(e)}")

    @property
    def _input_keys(self) -> set:
        return {"query_str"}
        
    @property
    def _output_keys(self) -> set:
        return {"json_str"}
    
# -- Build Pipeline Function --
def build_query_pipeline(cohere_model, df, classification_template):
    classify = ClassifyStepComponent(cohere_model, classification_template, df)
    execute = ExecutePlanComponent(df)
    
    # Explicitly connect components
    pipeline = QueryPipeline()
    pipeline.add_modules({
        "classify": classify,
        "execute": execute
    })
    pipeline.add_chain(["classify", "execute"])
    
    return pipeline

# Usage
pipeline = build_query_pipeline(cohere_model, df, classification_template)
result = pipeline.run(query_str="What is the sum of Compensation and Wages in 2023?")
print("Final result:", result)

TypeError: sequence item 0: expected str instance, int found

In [ ]:
"""
    # Handle the current format
if "items" in parsed:
    context = {}
    for i, item in enumerate(parsed["items"], 1):
        parts = [p.strip() for p in item.split(",")]
        if len(parts) == 2:  # field, year
            field, year = parts
            context[f"step{i}"] = extract_vals_from_df(df, field, year)
    return context
"""

In [490]:
clean.columns = clean.columns.astype(str)  # Ensure years are strings
clean.index = clean.index.str.strip()  # Remove whitespace from index

In [497]:
pipeline = build_query_pipeline(cohere_model, clean, classification_template)

response = pipeline.run(query_str="what percentage of Expense was spent on Wages in 2022?")
print(response)

ValidationError: 1 validation error for LLMChatStartEvent
messages.0.role
  Input should be 'system', 'user', 'assistant', 'function', 'tool', 'chatbot' or 'model' [type=enum, input_value='USER', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/enum

In [432]:
"""import json
import re

add = lambda a, b: a + b
multiply = lambda a, b: a * b
subtract = lambda a, b: a - b
divide = lambda a, b: a / b if (a is not None and b not in [0, None]) else None
return_percentage = lambda a, b: (a / b) * 100 if (a is not None and b not in [0, None]) else None

def classify_step(ch, query: str, df: pd.DataFrame = clean, template: PromptTemplate = classification_template) -> str:
  # redesign this such that 
  prompt = template.format(
    query=query,
    available_fields=", ".join(clean.index),
    available_years=", ".join(clean.columns),
  )
  response = ch.chat(model="command-r-08-2024", messages=[{"role": "user", "content": prompt}], temperature=0.1)
  return response.message.content[0].text

def extract_vals_from_df(df, col, year):
    return float(df.loc[col, year]) if col in df.index and year in df.columns else None

def retrieving(df, items):
    answer = []
    if len(items) == 2:
        col, year = items[0].strip(), items[1].strip()
        answer.append(extract_vals_from_df(df, col, year))
    else:
        answer.append(None)
    return answer

def advising(ch, query: str, df: pd.DataFrame = clean, template: PromptTemplate = advice_template) -> str:
  prompt = template.format(
    query=query,
    available_fields=", ".join(clean.index),
    available_years=", ".join(clean.columns),
    df = df.to_string()
  )
  response = ch.chat(model="command-r-08-2024", messages=[{"role": "user", "content": prompt}], temperature=0.1)
  return response.message.content[0].text

def executing_plan_from_json(df, json_str):
    parsed = json.loads(json_str)
    plan = parsed.get("plan", {})
    context = {}

    for step_name in sorted(plan.keys()):
        print(f"step is {step_name}")
        instruction = plan[step_name].strip()
        print(f"instruction is {instruction}")
        lowered = instruction.lower()
        pattern = r"'(.*?)'|\"(.*?)\""
        matches = re.findall(pattern, instruction)[0][0] if re.findall(pattern, instruction) else None
        matches = [m.strip() for m in matches.split(",")]
        print(f"matches are {matches}")
        if lowered.startswith("retrieve"):
            values = retrieving(df, matches)
            print(f"values are {values}")
            # update the context step with the retrieved values
            context[step_name] = values[0] if len(values) == 1 else values
            print(f"context this step is {context[step_name]}")
        else:
            resolved_vals = []
            for arg in matches: #
                if arg.startswith("step"):
                    val = context.get(arg)
                    print(val)
                    if val is None:
                        try:
                            val = float(arg)
                        except ValueError:
                            val = None
                    resolved_vals.append(val)
            print(f"resolved_vals are {resolved_vals}")

            if lowered.startswith("add") and len(resolved_vals) >= 2:
                context[step_name] = add(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("subtract") and len(resolved_vals) >= 2:
                context[step_name] = subtract(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("divide") and len(resolved_vals) >= 2:
                context[step_name] = divide(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("multiply") and len(resolved_vals) >= 2:
                context[step_name] = multiply(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("percentage") and len(resolved_vals) >= 2:
                context[step_name] = return_percentage(resolved_vals[0], resolved_vals[1])
            else:
                context[step_name] = None

    return context #[sorted(plan.keys())[-1]]"
    """

'import json\nimport re\n\nadd = lambda a, b: a + b\nmultiply = lambda a, b: a * b\nsubtract = lambda a, b: a - b\ndivide = lambda a, b: a / b if (a is not None and b not in [0, None]) else None\nreturn_percentage = lambda a, b: (a / b) * 100 if (a is not None and b not in [0, None]) else None\n\ndef classify_step(ch, query: str, df: pd.DataFrame = clean, template: PromptTemplate = classification_template) -> str:\n  # redesign this such that \n  prompt = template.format(\n    query=query,\n    available_fields=", ".join(clean.index),\n    available_years=", ".join(clean.columns),\n  )\n  response = ch.chat(model="command-r-08-2024", messages=[{"role": "user", "content": prompt}], temperature=0.1)\n  return response.message.content[0].text\n\ndef extract_vals_from_df(df, col, year):\n    return float(df.loc[col, year]) if col in df.index and year in df.columns else None\n\ndef retrieving(df, items):\n    answer = []\n    if len(items) == 2:\n        col, year = items[0].strip(), items[1].strip()\n        answer.append(extract_vals_from_df(df, col, year))\n    else:\n        answer.append(None)\n    return answer\n\ndef advising(ch, query: str, df: pd.DataFrame = clean, template: PromptTemplate = advice_template) -> str:\n  prompt = template.format(\n    query=query,\n    available_fields=", ".join(clean.index),\n    available_years=", ".join(clean.columns),\n    df = df.to_string()\n  )\n  response = ch.chat(model="command-r-08-2024", messages=[{"role": "user", "content": prompt}], temperature=0.1)\n  return response.message.content[0].text\n\ndef executing_plan_from_json(df, json_str):\n    parsed = json.loads(json_str)\n    plan = parsed.get("plan", {})\n    context = {}\n\n    for step_name in sorted(plan.keys()):\n        print(f"step is {step_name}")\n        instruction = plan[step_name].strip()\n        print(f"instruction is {instruction}")\n        lowered = instruction.lower()\n        pattern = r"\'(.*?)\'|"(.*?)""\n        matches = re.findall(pattern, instruction)[0][0] if re.findall(pattern, instruction) else None\n        matches = [m.strip() for m in matches.split(",")]\n        print(f"matches are {matches}")\n        if lowered.startswith("retrieve"):\n            values = retrieving(df, matches)\n            print(f"values are {values}")\n            # update the context step with the retrieved values\n            context[step_name] = values[0] if len(values) == 1 else values\n            print(f"context this step is {context[step_name]}")\n        else:\n            resolved_vals = []\n            for arg in matches: #\n                if arg.startswith("step"):\n                    val = context.get(arg)\n                    print(val)\n                    if val is None:\n                        try:\n                            val = float(arg)\n                        except ValueError:\n                            val = None\n                    resolved_vals.append(val)\n            print(f"resolved_vals are {resolved_vals}")\n\n            if lowered.startswith("add") and len(resolved_vals) >= 2:\n                context[step_name] = add(resolved_vals[0], resolved_vals[1])\n            elif lowered.startswith("subtract") and len(resolved_vals) >= 2:\n                context[step_name] = subtract(resolved_vals[0], resolved_vals[1])\n            elif lowered.startswith("divide") and len(resolved_vals) >= 2:\n                context[step_name] = divide(resolved_vals[0], resolved_vals[1])\n            elif lowered.startswith("multiply") and len(resolved_vals) >= 2:\n                context[step_name] = multiply(resolved_vals[0], resolved_vals[1])\n            elif lowered.startswith("percentage") and len(resolved_vals) >= 2:\n                context[step_name] = return_percentage(resolved_vals[0], resolved_vals[1])\n            else:\n                context[step_name] = None\n\n    return context #[sorted(plan.keys())[-1]]"\n    '

In [ ]:
output = StructuredParserComponent(classification_template, ClassificationPlan, cohere_model).run_component(
    query_str="What is the Expense in 2022?",
    available_fields=", ".join(clean.index),
    available_years=", ".join(clean.columns)
)

In [ ]:
class TaskRouterComponent(CustomQueryComponent):
    def __init__(self, df: pd.DataFrame, year: str):
        self.df = df

    def _run_component(self, **kwargs) -> Dict[str, Any]:
        parsed = kwargs["parsed_output"]

        if parsed.task_type == "retrieve_numbers":
            result = retrieving(self.df, parsed.items)
        elif parsed.task_type == "perform_calculations":
            result = executing_plan_from_json(self.df, parsed.plan)  # assumes helper exists
        elif parsed.task_type == "give_advice":
            result = advising(self.df, parsed['description'])
        else:
            result = "Task type not recognized. Will enable support for this task type soon."

        return {"final_result": result}

    @property
    def _input_keys(self): return {"parsed_output"}
    @property
    def _output_keys(self): return {"final_result"}

Plan execution for perform_calculations

In [194]:
class MyFunctionComponent(CustomQueryComponent):
    def __init__(self, fn, input_keys: list[str], output_key: str):
        self.fn = fn
        self.input_keys_set = set(input_keys)
        self.output_key = output_key
        self.input_keys_list = input_keys

    def _run_component(self, **kwargs):
        inputs = {k: kwargs[k] for k in self.input_keys_list}
        result = self.fn(**inputs)
        return {self.output_key: result}

    @property
    def input_keys(self): return self.input_keys_set
    @property
    def output_keys(self): return {self.output_key}

In [ ]:
add = lambda a, b: a + b
multiply = lambda a, b: a * b
subtract = lambda a, b: a - b
divide = lambda a, b: a / b if b != 0 else 0
return_percentage = lambda a, b: (a / b) * 100 if b != 0 else 0

def extract_vals_from_df(df, col, year):
    return float(df.loc[col, year])

In [ ]:
divide_component = MyFunctionComponent(
    fn=divide,
    input_keys=["value1", "value2"],
    output_key="divide_result"
)

add_component = MyFunctionComponent(
    fn=add,
    input_keys=["value1", "value2"],
    output_key="add_result"
)

subtract_component = MyFunctionComponent(
    fn=subtract,
    input_keys=["value1", "value2"],
    output_key="subtract_result"
)

multiply_component = MyFunctionComponent(
    fn=multiply,
    input_keys=["value1", "value2"],
    output_key="multiply_result"
)

percentage_component = MyFunctionComponent(
    fn=return_percentage,
    input_keys=["value1", "value2"],
    output_key="percentage_result"
)

structured_parser = StructuredParserComponent(
    prompt_template=qa_template,
    schema=ClassificationPlan,
    model="command-r-08-2024",
    api_key=cohere_api
)

Synthesis component

In [ ]:
class CohereSynthesisComponent(CustomQueryComponent):
    def __init__(self, llm=None):
        self.llm = llm or Cohere(model="command-r")

    def _run_component(self, **kwargs):
        result = kwargs["final_result"]
        user_query = kwargs["query_str"]

        prompt = f"""
        You are a financial assistant. Based on this result: {result}
        Answer the user's query: {user_query}
        """

        response = self.llm.complete(prompt=prompt)
        return {"synthesized_output": response.text}

    @property
    def _input_keys(self): return {"final_result", "query_str"}
    @property
    def _output_keys(self): return {"synthesized_output"}

define pipeline

In [ ]:
from llama_index.core import VectorStoreIndex
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.query_pipeline import QueryPipeline, CustomQueryComponent
from llama_index.core.llms import ChatMessage, MessageRole
from llama_index.core.prompts import PromptTemplate

pipeline = QueryPipeline(chain=[
    StructuredParserComponent(classification_template),  # LLM → JSON
    TaskRouterComponent(df=clean),                      # Decision + Action
    CohereSynthesisComponent()                          # Summarize Final Answer
])

In [ ]:
res = pipeline.run(
    query_str="What is the ratio of revenue to expense in 2022?",
    available_fields=clean.index,
    available_years=clean.columns,
)
print(res["answer"])

In [154]:
classification_schema = {
    "type": "object",
    "properties": {
        "task_type": {
            "type": "string",
            "enum": ["retrieve_numbers", "give_advice", "perform_calculations", "other"]
        },
        "description": {"type": "string"},  # For advice
        "items": {  # For retrieval
            "type": "array",
            "items": {"type": "string"}
        },
        "plan": {  # For calculations - now an object, not a list
            "type": "object",
            "properties": {
                "steps": {
                    "type": "array",
                    "items": {"type": "string"}
                }
            },
            "required": ["steps"]
        }
    },
    "required": ["task_type"],
    "oneOf": [
        {"required": ["task_type", "items"], "properties": {"task_type": {"const": "retrieve_numbers"}}},
        {"required": ["task_type", "description"], "properties": {"task_type": {"const": "give_advice"}}},
        {"required": ["task_type", "plan"], "properties": {"task_type": {"const": "perform_calculations"}}},
        {"required": ["task_type"], "properties": {"task_type":{"const": "other"}}}  # Handle the "other" case
    ],
    "additionalProperties": False  # Good practice: prevent unexpected keys
}

In [ ]:
def get_llm_classify(query: str, available_fields: list, available_years: list,
                   llm: Cohere = cohere_model, template: str = classification_template, 
                   response_schema: dict = classification_schema) -> dict:
    
    """Classifies the user's query and returns a dictionary with task information.

    Args:
        query: The user's query string.
        available_fields: A list of available data field names (strings).
        available_years: A list of available years (strings).
        model: The Cohere model name. Defaults to "command".
        template: The prompt template string.

    Returns:
        A dictionary containing the parsed JSON response from the LLM, or
        an empty dictionary if an error occurs.
    """

    # 1. Format the prompt
    formatted_prompt = PromptTemplate(classification_template).format(
        query_str=query,
        available_fields=available_fields.tolist(),
        available_years=available_years.tolist()
    )

    # 2. Pass prompt to the LLM
    response = llm.chat(
        messages = [ChatMessage(role=MessageRole.USER, content=formatted_prompt)],
        response_format={"type": "json_object"},
        temperature=0.1
    )

    # 3. Get the response
    answer = response.message.content[0].text
    return answer 
"""
    # 4. Validate the response
    structured_output = json.loads(answer)
    # Manually transform the output if necessary to match your schema
    # This step depends on the structure of your LLM output and the desired final format
    transformed_output = structured_output  # Placeholder for transformation logic
    # Validate the transformed output against your custom JSON schema
    validate(instance=transformed_output, schema=classification_schema)
    print(transformed_output)"
"""

In [175]:
?llm.chat

Object `llm.chat` not found.

#### Calculation

In [398]:
from pydantic import BaseModel, Field
from typing import Literal, Dict

class CalculationPlan(BaseModel):
    task_type: Literal["perform_calculations"]
    plan: Dict[str, str]

In [399]:
import json
import re

add = lambda a, b: a + b
multiply = lambda a, b: a * b
subtract = lambda a, b: a - b
divide = lambda a, b: a / b if (a is not None and b not in [0, None]) else None
return_percentage = lambda a, b: (a / b) * 100 if (a is not None and b not in [0, None]) else None

def extract_vals_from_df(df, col, year):
    return float(df.loc[col, year]) if col in df.index and year in df.columns else None

def retrieving(df, items):
    answer = []
    if len(items) == 2:
        col, year = items[0].strip(), items[1].strip()
        answer.append(extract_vals_from_df(df, col, year))
    else:
        answer.append(None)
    return answer

def execute_plan_from_json(df, json_str, calculation_plan: BaseModel = CalculationPlan):
    # parsed = json.loads(json_str)
    parsed = CalculationPlan.model_validate_json(json_str)
    # plan = parsed.get("plan", {})
    plan = parsed.plan
    context = {}

    for step_name in sorted(plan.keys()):
        print(f"step is {step_name}")
        instruction = plan[step_name].strip()
        print(f"instruction is {instruction}")
        lowered = instruction.lower()
        pattern = r"'(.*?)'|\"(.*?)\""
        matches = re.findall(pattern, instruction)[0][0] if re.findall(pattern, instruction) else None
        matches = [m.strip() for m in matches.split(",")]
        print(f"matches are {matches}")
        if lowered.startswith("retrieve"):
            values = retrieving(df, matches)
            print(f"values are {values}")
            # update the context step with the retrieved values
            context[step_name] = values[0] if len(values) == 1 else values
            print(f"context this step is {context[step_name]}")
        else:
            resolved_vals = []
            for arg in matches: #
                if arg.startswith("step"):
                    val = context.get(arg)
                    print(val)
                    if val is None:
                        try:
                            val = float(arg)
                        except ValueError:
                            val = None
                    resolved_vals.append(val)
            print(f"resolved_vals are {resolved_vals}")

            if lowered.startswith("add") and len(resolved_vals) >= 2:
                context[step_name] = add(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("subtract") and len(resolved_vals) >= 2:
                context[step_name] = subtract(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("divide") and len(resolved_vals) >= 2:
                context[step_name] = divide(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("multiply") and len(resolved_vals) >= 2:
                context[step_name] = multiply(resolved_vals[0], resolved_vals[1])
            elif lowered.startswith("percentage") and len(resolved_vals) >= 2:
                context[step_name] = return_percentage(resolved_vals[0], resolved_vals[1])
            else:
                context[step_name] = None

    return context#[sorted(plan.keys())[-1]]

In [ ]:
pipeline = QueryPipeline(
    chain=[
        ,
        llm.as_query_component(streaming=True),
        output_parser,
    ],
    verbose=True,
)
output = pipeline.run()
print(output)

In [342]:
output0

'{\n    "task_type": "perform_calculations",\n    "plan": {\n        "step1": "retrieve [\'Wages and salaries, 2022\']",\n        "step2": "retrieve [\'Compensation of employees, 2022\']",\n        "step3": "add [\'step1, step2\']",\n        "step4": "retrieve [\'Expense, 2022\']",\n        "step5": "divide [\'step3, step4\']",\n        "step6": "multiply [\'step5, 100\']"\n    }\n}'

In [385]:
import re

text = "add ['step1', 'step2']"
instruction = "retrieve [\'Wages and salaries, 2022\']"
pattern = r"'(.*?)'|\"(.*?)\""

matches = re.findall(pattern, instruction)[0][0]
# items = [m[0] or m[1] for m in matches]
matches = [m.strip() for m in matches.split(",")]  # ['step1', 'step2']
matches = tuple(matches)
matches

('Wages and salaries', '2022')

In [363]:
col, year = matches[0].strip(),  matches[1].strip()
print(extract_vals_from_df(clean, col, year))

88171.21

In [353]:
len(matches)

24

In [ ]:
matches = ['step1, step2']
args = [matches[0].split(",")[0].strip()] + [matches[0].split(",")[1].strip()] if matches else []
args

['step1', 'step2']

In [ ]:
m = "step1, step2"

In [392]:
output0

'{\n    "task_type": "perform_calculations",\n    "plan": {\n        "step1": "retrieve [\'Wages and salaries, 2022\']",\n        "step2": "retrieve [\'Compensation of employees, 2022\']",\n        "step3": "add [\'step1, step2\']",\n        "step4": "retrieve [\'Expense, 2022\']",\n        "step5": "divide [\'step3, step4\']",\n        "step6": "multiply [\'step5, 100\']"\n    }\n}'

1. test cases 

2. demo (front end + back end integration)

3. time permitting, allow basic plotting features (bar, scatter, box, heatmap)

In [391]:
ans = execute_plan_from_json(clean, output0)
ans

step is step1
instruction is retrieve ['Wages and salaries, 2022']
matches are ['Wages and salaries', '2022']
values are [88171.21]
context this step is 88171.21
step is step2
instruction is retrieve ['Compensation of employees, 2022']
matches are ['Compensation of employees', '2022']
values are [102368.29]
context this step is 102368.29
step is step3
instruction is add ['step1, step2']
matches are ['step1', 'step2']
88171.21
102368.29
resolved_vals are [88171.21, 102368.29]
step is step4
instruction is retrieve ['Expense, 2022']
matches are ['Expense', '2022']
values are [389392.489]
context this step is 389392.489
step is step5
instruction is divide ['step3, step4']
matches are ['step3', 'step4']
190539.5
389392.489
resolved_vals are [190539.5, 389392.489]
step is step6
instruction is multiply ['step5, 100']
matches are ['step5', '100']
0.48932505218404454
resolved_vals are [0.48932505218404454]

{'step1': 88171.21,
 'step2': 102368.29,
 'step3': 190539.5,
 'step4': 389392.489,
 'step5': 0.48932505218404454,
 'step6': None}

In [233]:
clean.index

Index(['Expense', 'Compensation of employees', 'Wages and salaries',
       'Employers' social contributions', 'Use of goods and services',
       'Consumption of fixed capital', 'Interest expense', 'To nonresidents',
       'To residents other than government units', 'To other government units',
       'Subsidies', 'To public corporations', 'To private enterprises',
       'To other sectors', 'Grants', 'To foreign governments',
       'To international organizations', 'To other government units',
       'Current', 'Capital', 'Social benefits', 'Social security benefits',
       'Social assistance benefits', 'Employment-related social benefits',
       'Other expense', 'Property expense other than interest',
       'Expense on other transfers'],
      dtype='object', name='category')

In [ ]:
from typing import Dict, Any, List
import pandas as pd
from llama_index.llms import Cohere
from llama_index.core.query_pipeline import QueryPipeline, CustomQueryComponent

# Define a plan-based step executor
def execute_plan(plan: List[str], df: pd.DataFrame, year: str) -> Dict[str, Any]:
    results = {}
    for step in plan:
        tokens = step.lower().split()
        if "retrieve" in tokens:
            field = step.split("retrieve")[-1].strip()
            results[field] = float(df.loc[field, year]) if field in df.index else None
        elif "add" in tokens:
            fields = step.replace("add", "").split("and")
            a, b = [results.get(f.strip(), 0) for f in fields]
            results[step] = a + b
        elif "multiply" in tokens:
            fields = step.replace("multiply", "").split("and")
            a, b = [results.get(f.strip(), 0) for f in fields]
            results[step] = a * b
        elif "divide" in tokens:
            fields = step.replace("divide", "").split("by")
            a, b = [results.get(f.strip(), 0) for f in fields]
            results[step] = a / b if b != 0 else None
        elif "percentage" in tokens:
            fields = step.replace("percentage", "").split("of")
            a, b = [results.get(f.strip(), 0) for f in fields]
            results[step] = (a / b) * 100 if b != 0 else None
    return results

# Custom query component for processing plans
class PlanExecutionComponent(CustomQueryComponent):
    def __init__(self, df: pd.DataFrame, year: str):
        self.df = df
        self.year = year

    def _run_component(self, **kwargs) -> Dict[str, Any]:
        plan = kwargs.get("plan", [])
        results = execute_plan(plan, self.df, self.year)
        return {"processed_data": results}

    @property
    def _input_keys(self) -> set:
        return {"plan"}

    @property
    def _output_keys(self) -> set:
        return {"processed_data"}

# Example dataframe
example_df = pd.DataFrame({
    "2022": [60000, 12000, 3000],
}, index=["Wages and salaries", "Expense", "Bonuses"])

# Example plan
plan = [
    "retrieve Wages and salaries",
    "retrieve Expense",
    "divide Wages and salaries by Expense"
]

# Build and run pipeline
cohere_model = Cohere(model="command")
pipeline = QueryPipeline(chain=[PlanExecutionComponent(example_df, "2022"), cohere_model], verbose=True)

response = pipeline.run(plan=plan)
print(response["processed_data"])

In [ ]:
# class ExtractValsInput(BaseModel):
#     """Input for extracting values from the DataFrame."""
#     year: int = Field(..., description="The year to retrieve data for.")
#     col1: str = Field(..., description="The name of the first column to extract.")
#     col2: str = Field(..., description="The name of the second column to extract.")

In [128]:
from llama_index.core.query_pipeline import QueryPipeline

In [28]:
calculation_template = """
    You are a financial assistant. Generate a JSON object representing a *single*
    calculation step, based on the provided description.
    Available functions: addition, subtraction, division, multiplication, percentage
    You are to find the right names for field1 and field2, as the query may not contain the exact word. 

    Output Format:
    ```json
    {
    "function": "name_of_function",
    "year": "year",
    "field1": "field_name_1",
    "field2": "field_name_2"
    }
"""

In [122]:
calculation_schema = {
    "type": "object",
    "properties": {
        "function": {
            "type": "string",
            "enum": ["addition", "subtraction", "division", "multiplication", "percentage"]
        },
        "year": {"type": "string"},
        "field1": {"type": "string"},
        "field2": {"type": "string"}
    },
    "required": ["function", "year", "field1", "field2"],
    "additionalProperties": False  # Prevent extra keys
}

In [ ]:
# Define prompt templates

prompt_str1 = "Please generate a concise question about (topic)"
prompt_tmpl1 = PromptTemplate(prompt_str1)

prompt_str2 = "Please write a passage to answer the question: {query_str}"
prompt_tmpl2 = PromptTemplate(prompt_str2)

# Create a query pipeline
pipeline = QueryPipeline(chain=[prompt_tmpl1, cohere_model, prompt_tmpl2, cohere_model], verbose=True)
# Run the pipeline
output = pipeline.run(topic="college")

In [ ]:
PromptTemplate(classification_template).format(query_str=query, available_fields=clean.index, available_years=clean.columns)

#### Agentic Tools (Depreciated)

In [46]:
def create_retrieve_tool(df, col=None, year=None):
    def extract_vals_from_df(df, col, year):
        return float(df.loc[col, year])
    return FunctionTool.from_defaults(fn=extract_vals_from_df)

In [ ]:
from pydantic import BaseModel, Field
from typing import Type

In [56]:
import pandas as pd
from llama_index.core.tools import FunctionTool, ToolMetadata
from llama_index.core.agent import ReActAgent
from llama_index.core import VectorStoreIndex, ServiceContext
from pydantic import BaseModel, Field
from typing import List, Dict, Tuple, Any

In [89]:
import pandas as pd
from typing import List, Dict, Any
from pydantic import BaseModel, Field

# --- Your existing function (slightly modified for standalone testing)---
def extract_vals_from_df(year: str, rows: List[str], df: pd.DataFrame) -> Dict[str, Any]:
    df = pd.DataFrame(df)  # Convert the list of dictionaries to a DataFrame
    return {r: float(df.loc[r, year]) for r in rows}

# --- Test Cases ---
print(extract_vals_from_df(year="2022", rows=['Capital', 'Wages and salaries'], df=clean))  # Correct usage

{'Capital': 9520.7, 'Wages and salaries': 88171.21}

In [ ]:
# # --- Pydantic Input Model ---
# from typing import List, Dict, Any
# from pydantic import BaseModel, Field
# from llama_index.core.tools import FunctionTool
# from llama_index.core.agent import ReActAgent
# from llama_index.core import VectorStoreIndex

# class ExtractValsInput(BaseModel):
#     year: int
#     rows: List[str]
#     df: pd.DataFrame

# def extract_vals_from_df(year: int, rows: List[str], df: pd.DataFrame) -> Dict[str, Any]:
#     year_str = str(year)
#     if year_str not in df.columns:
#         return {}
#     return {r: df.loc[r, year_str] if r in df.index else None for r in rows}

# def extract_vals_wrapper(**kwargs) -> Dict[str, Any]:
#     input_data = ExtractValsInput(**kwargs)
#     return extract_vals_from_df(input_data.year, input_data.rows, input_data.df)

# add = lambda a, b: a + b
# multiply = lambda a, b: a * b
# subtract = lambda a, b: a - b
# divide = lambda a, b: a / b if b != 0 else 0
# return_percentage = lambda a, b: (a / b) * 100 if b != 0 else 0

# agent_tools = [FunctionTool.from_defaults(fn=f) 
#                for f in (add, multiply, subtract, divide, return_percentage)
#                ] + [FunctionTool.from_defaults(fn=extract_vals_wrapper, fn_schema=ExtractValsInput)]

# agent = ReActAgent.from_tools(
#     tools=agent_tools,
#     llm=cohere_model,
#     verbose=True,
# )

# data = {'2021': [50000, 10000], '2022': [60000, 12000], '2023': [70000, 15000]}
# df = pd.DataFrame(data, index=['Wages and salaries', 'Expense'])

# response = agent.query(
#     query_str="What is the Wages and salaries to Expense ratio for 2022?",
#     df=df
# )
# print(response)

In [ ]:
# ?FunctionTool.from_defaults

In [ ]:
# class ExtractValsInput(BaseModel):
#     """Input for extracting values from the DataFrame."""
#     year: int = Field(..., description="The year to retrieve data for.")
#     col1: str = Field(..., description="The name of the first column to extract.")
#     col2: str = Field(..., description="The name of the second column to extract.")

In [ ]:
# add_tool = FunctionTool.from_defaults(fn=add)
# multiply_tool = FunctionTool.from_defaults(fn=multiply)
# subtract_tool = FunctionTool.from_defaults(fn=subtract)
# divide_tool = FunctionTool.from_defaults(fn=divide)
# percentage_tool = FunctionTool.from_defaults(fn=return_percentage)

# retrieve_tool = create_retrieve_tool(clean)

# agent_tools = [add_tool, multiply_tool, subtract_tool, divide_tool, percentage_tool, retrieve_tool]

# agent = ReActAgent.from_tools(agent_tools, llm=cohere_model, verbose=True)

# # Example: Create a simple index (you might have a different index)
# # For this example, we'll just create an empty index, as the tools are the focus.
# index = VectorStoreIndex([])

# # --- 4. Create the ReActAgent ---
# agent = ReActAgent.from_tools(
#     tools=agent_tools,
#     llm=cohere_model,
#     verbose=True,  # Enable verbose output to see the agent's reasoning
# )
# # --- 5. Query the Agent ---

# response = agent.query("What is the debt to equity ratio of my company for 2022?")
# print(response)

#### Retrieval

In [ ]:
def retrieving(df, items):
    answer = []
    for i in items:
        col, year = i.split(",")[0].strip(), i.split(",")[1].strip()
        # print(col)
        # print(year)
        answer.append(extract_vals_from_df(df, col, year))
    return answer

In [487]:
def retrieval(df, items):
    answer = []
    if len(items) == 2:
        col = items[0].strip().strip("'\"")  # Clean extra quotes
        year = items[1].strip().strip("'\"")
        print(f"🔎 Retrieving: column='{col}', year='{year}'")
        answer.append(extract_vals_from_df(df, col, year))
    else:
        answer.append(None)
    return answer

In [ ]:
items = ["Expense, 2022", "Capital, 2022"]
answer = retrieving(clean, items)

In [489]:
answer = retrieval(clean, items)
type(answer)

🔎 Retrieving: column='Expense, 2022', year='Capital, 2022'

list

In [ ]:
def execute_retrieval(step: Dict[str, Any], df: pd.DataFrame) -> Union[float, str]:
    """
    Executes a retrieval step based on the provided step and DataFrame.
    
    Args:
        step: A dictionary containing the step information.
        df: The DataFrame containing the financial data.
    
    Returns:
        The result of the retrieval step, or an error message.
    """
    try:
        field = step["field"]
        year = step["year"]
        return extract_vals_from_df(df, field, year)
    except Exception as e:
        return f"Error executing retrieval step: {e}"

In [113]:
output1 = get_llm_answer(query="What is the Employee Wages for 2023", template=classification_template)

The `response_format.schema` parameter is an experimental feature and may change in future releases.
To suppress this warning, set `log_warning_experimental_features=False` when initializing the client.

Final answer:
{
  "task_type": "retrieve_numbers",
  "plan": [
    "Employee Wages, 2023"
  ]
}

In [114]:
items

['Expense, 2022', 'Capital, 2022']

In [ ]:
from pydantic import BaseModel

# Define Pydantic models
class DataModel(BaseModel):
    key1: str
    key2: int

In [ ]:
data = DataModel.model_validate_json()
# Call Python function
processed_result = process_data(data)
# Return processed result to LLM for final output
final_prompt = f"Generate a final output using the processed data: {processed_result}"
final_output = .complete(final_prompt)
print(final_output)

'{\n  "task_type": "retrieve_numbers",\n  "plan": [\n    "employee_wages, 2023"\n  ]\n}'

In [ ]:
output2 = get_llm_classify(query="What is the total expenses and capital of 2023", available_fields=list(clean.index), 
                         model=cohere_model, available_years=list(clean.columns), template=classification_template)

In [140]:
output3 = get_llm_answer(query="how I can cut my operational costs for 2025", template=classification_template)

The `response_format.schema` parameter is an experimental feature and may change in future releases.
To suppress this warning, set `log_warning_experimental_features=False` when initializing the client.

Final answer:
{
    "task_type": "give_advice",
    "description": "strategies to reduce operational costs for 2025"
}

In [141]:
output4 = get_llm_answer(query="what is the capital to equity ratio in 2022", template=classification_template)

The `response_format.schema` parameter is an experimental feature and may change in future releases.
To suppress this warning, set `log_warning_experimental_features=False` when initializing the client.

Final answer:
{
  "task_type": "perform_calculations",
  "plan": [
    "1: Calculate or retrieve the capital for the year 2022.",
    "2: Calculate or retrieve the equity for the year 2022.",
    "3: Divide the capital by the equity to find the capital to equity ratio for 2022."
  ]
}

In [113]:
output5 = get_llm_answer(query="What is the debt to equity ratio in 2022", template=classification_template)

The `response_format.schema` parameter is an experimental feature and may change in future releases.
To suppress this warning, set `log_warning_experimental_features=False` when initializing the client.

Final answer:
{
    "task_type": "perform_calculations",
    "plan": [
        "Retrieve the total debt of the company for the year 2022.",
        "Retrieve the total equity of the company for the year 2022.",
        "Calculate the debt to equity ratio by dividing the total debt by the total equity."
    ]
}

————————————————————————————————————————————

1. Test some edge cases (or extreme cases where the classification doesn't match one of the 3).
 
2. what if there is retrieval step within the plan for calculation?

————————————————————————————————————————————

NOTE:

Now we can define another function that would take the output2 and finish the task. 
Another possibility to explore is chain-of-thought (or equivalent) for the llama index.

In [ ]:
index_list = df.index.to_list()
index_string = ", ".join(index_list)  # Comma-separated string

In [32]:
# !pip install jsonschema
import jsonschema

In [ ]:
clean.index.to_list()

In [122]:
output6 = get_llm_answer(query="What is the debt to equity ratio in 2022", template=classification_template)

The `response_format.schema` parameter is an experimental feature and may change in future releases.
To suppress this warning, set `log_warning_experimental_features=False` when initializing the client.

Final answer:
{
  "task_type": "perform_calculations",
  "plan": [
    "Retrieve the total debt for the company in 2022.",
    "Retrieve the total equity for the company in 2022.",
    "Calculate the debt to equity ratio by dividing the total debt by the total equity."
  ]
}

In [123]:
task_info = json.loads(output6)
print(jsonschema.validate(instance=task_info, schema=response_schema))
task_type = task_info["task_type"]
plan = task_info.get("plan")
plan

None

['Retrieve the total debt for the company in 2022.',
 'Retrieve the total equity for the company in 2022.',
 'Calculate the debt to equity ratio by dividing the total debt by the total equity.']

In [126]:
results = []
intermediate_results = {}

for i, step_description in enumerate(plan):
    # --- Step 2: Generate JSON for *each* calculation step ---
    step_prompt = PromptTemplate(calculation_template).format(step_description=step_description)
    response = cohere_model.complete(step_prompt)
    response_text = response.text
    print(response_text)

try:
    step_json = json.loads(response_text)
    jsonschema.validate(instance=step_json, schema=calculation_step_schema)

    # --- Step 3: Execute the Calculation ---
    result = execute_calculation(step_json, df)

    if isinstance(result, str): #Check if result is an error
        print(result) #Return immediately

    results.append(result)
    intermediate_results[f"result_{i+1}"] = result  # Store

except (json.JSONDecodeError, jsonschema.ValidationError) as e:
    print(f"Error in JSON generation for step {i+1}: {e}. Response text: {response_text}")

```json
{
  "function": "addition",
  "year": "2023",
  "field1": "Revenue",
  "field2": "Projected_Income"
}
```
```json
{
  "function": "addition",
  "year": "2023",
  "field1": "Revenue",
  "field2": "Projected_Sales"
}
```
```json
{
  "function": "addition",
  "year": "2023",
  "field1": "Revenue",
  "field2": "Projected Growth"
}
```
Error in JSON generation for step 3: Expecting value: line 1 column 1 (char 0). Response text: ```json
{
  "function": "addition",
  "year": "2023",
  "field1": "Revenue",
  "field2": "Projected Growth"
}
```

In [ ]:
def execute_calculation(step: Dict[str, Any], df: pd.DataFrame) -> Union[float, str]:
    """Executes a single calculation step.

    Args:
        step: A dictionary representing the calculation step (conforming to calculation_step_schema).
        df: The Pandas DataFrame containing the financial data.

    Returns:
        The result of the calculation, or an error string.
    """
    function_name = step.get("function")
    if not function_name:
        return "Error: 'function' key missing."

    function_map: Dict[str, Callable] = {
        "addition": add,
        "subtraction": subtract,
        "division": divide,
        "multiplication": multiply,
        "percentage": return_percentage
    }

    function = function_map.get(function_name)
    if not function:
        return f"Error: Function '{function_name}' not found."

    try:
        year = step["year"]
        field1 = step["field1"]
        args = {field1 : extract_vals_from_df(df, field1, year)} #Create args dynamically
        if "field2" in step:
            field2 = step["field2"]
            args[field2] = extract_vals_from_df(df, field2, year) #Create args dynamically

        return function(**args) #Call the function
    except (KeyError, TypeError, ValueError) as e:
        return f"Error during data retrieval or calculation: {e}"
    except Exception as e:
        return f"Unexpected Error {e}"

# --- Main Query Function ---
def my_rag_query(query_str: str, df: pd.DataFrame, llm=cohere_model) -> str:
    """Processes a financial query, handling calculations and retrieval."""

    # --- Step 1: Task Classification and Planning ---
    classification_prompt = PromptTemplate(classification_template).format(query_str=query_str)
    response = llm.complete(classification_prompt)
    response_text = response.text.strip()  # Remove leading/trailing whitespace

    try:
        # load as a json file because LLM will always return strings, even if they are formatted as JSON
        task_info = json.loads(response_text)
        # validate the json string so that we know what we are working with
        jsonschema.validate(instance=task_info, schema=response_schema)
        # return the task type
        task_type = task_info["task_type"]
    except (json.JSONDecodeError, jsonschema.ValidationError) as e:
        return f"Error in task classification: {e}, Response Text: {response_text}"
    # start categorizing the task and call the corresponding function to complete the task
    if task_type == "retrieve_numbers":
        items = task_info.get("plan")
        if not items:
            return "Error: No retrieval items found."
        # put the items as arguments to the python function to retrieve

    elif task_type == "give_advice":
        return "Error. Advice not implemented"

    elif task_type == "perform_calculations":
        plan = task_info.get("plan")
        if not plan:
            return "Error: Calculation task requires a plan."

        results = []
        intermediate_results = {}
        for i, step_description in enumerate(plan):
            # --- Step 2: Generate JSON for *each* calculation step ---
            step_prompt = PromptTemplate(calculation_template).format(step_description=step_description)
            response = llm.complete(step_prompt)
            response_text = response.text.strip() #Remove extra text.

            step_json = None  # Initialize step_json *outside* the try block
            try:
                # Attempt to parse and validate JSON.  Handle errors gracefully.
                step_json = json.loads(response_text)
                jsonschema.validate(instance=step_json, schema=calculation_step_schema)

                # --- Step 3: Execute the Calculation ---
                result = execute_calculation(step_json, df)
                if isinstance(result, str):
                    return result #Return error if string

                results.append(result)
                intermediate_results[f"result_{i+1}"] = result

            except (json.JSONDecodeError, jsonschema.ValidationError) as e:
                return f"Error in JSON generation/validation for step {i+1}: {e}.  Response text: {response_text}"
            except Exception as e:  # Catch any other exceptions during execution
                return f"Error in step {i + 1}: {e}"

        return str(results)

    else:
        return f"Error: Unsupported task type: {task_type}"

In [121]:
my_rag_query(query_str="What was the debt to equity ratio in 2022", df=clean)

'Error in task classification: Expecting property name enclosed in double quotes: line 1 column 2 (char 1), Response Text: {{\n    "task_type": "retrieve_numbers",\n    "description": "retrieve revenue data for the year 2023"\n}}'

In [ ]:
# !pip install llama-index-question-gen-guidance

In [ ]:
# # --- LlamaIndex Setup ---
# # (Load documents, create index - same as before. I will include for completeness)
# with open("data.txt", "w") as f:
#     f.write(
#         "In 2023, the company had a Revenue of 1000, Expenses of 100, Capital of 500, and Debt of 200.\n"
#         "In 2024, Revenue was 1100, Expenses were 120, Capital was 600, and Debt was 250."
#     )
# documents = SimpleDirectoryReader(input_files=["data.txt"]).load_data()

# data = {
#     "2023": {"Expense": 100.0, "Capital": 500.0, "Revenue": 1000.0, "Debt": 200.0},
#     "2024": {"Expense": 120.0, "Capital": 600.0, "Revenue": 1100.0, "Debt": 250.0},
# }
# df = pd.DataFrame.from_dict(data, orient='index')
# df = df.transpose()

In [ ]:
# %pip install llama-index-question-gen-guidance

In [ ]:
# !pip install llama-index
# !pip install guidance

Refer to:

https://docs.llamaindex.ai/en/stable/examples/output_parsing/llm_program/
https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/service_context_migration/
https://github.com/guidance-ai/guidance/tree/main?tab=readme-ov-file#loading-models

In [26]:
import os
from dotenv import load_dotenv

load_dotenv()
# Load the Cohere API key from the environment variable
openai_api = os.getenv("OPENAI_API_KEY")

# Initialize the OpenAI model
# from llama_index.llms import OpenAI 
from guidance.models import OpenAI

In [27]:
openai_api

'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'

In [33]:
prompt_template_str = (
    "You are a financial assistant.  Given the user query, "
    "determine the necessary calculation and output a `CalculationInput` object.\n"
    "Available functions are: addition, subtraction, division, multiplication, percentage\n\n"
    "The `CalculationInput` object has the following fields:\n"
    "  - `function`: (str) The name of the function to call (required).\n"
    "  - `year`: (str) The year for the financial data (required).\n"
    "  - `field1`: (str) The name of the first field (e.g., 'Revenue', 'Debt') (required).\n"
    "  - `field2`: (str) The name of the second field.  *Only required for functions that need two inputs*.\n\n"  # Clarified field2
    "User Query: {query_str}\n"
    "CalculationInput:"
)

In [ ]:
prompt_template_str = (
    "You are a financial assistant.  Given the user query, "
    "determine the necessary calculation and output a `CalculationInput` object.\n"
    "Available functions are: addition, subtraction, division, multiplication, percentage\n\n"
    "The `CalculationInput` object has the following fields:\n"
    "  - `function`: (str) The name of the function to call (required).\n"
    "  - `year`: (str) The year for the financial data (required).\n"
    "  - `field1`: (str) The name of the first field (e.g., 'Revenue', 'Debt') (required).\n"
    "  - `field2`: (str) The name of the second field.  *Only required for functions that need two inputs*.\n\n"
    "User Query: {query_str}\n"
    "CalculationInput:"
)

Solved: https://github.com/run-llama/llama_index/issues/9914

In [34]:
prompt_template_str = """
You are a financial assistant. Your task is to translate a user's financial calculation request into a `CalculationInput` object.

A `CalculationInput` object has the following structure:
```python
class CalculationInput(BaseModel):
    function: str  # The name of the function (addition, subtraction, division, multiplication, percentage)
    year: str      # The year for the data
    field1: str    # The first field name (e.g., Revenue, Debt, Expenses, Capital)
    field2: Optional[str] # The second field name (only needed for some functions like division)" \
    """

#### Query Engine

In [ ]:
from typing import List, Callable, Union
from pydantic import BaseModel, Field
# from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext, PromptTemplate
from llama_index.program.guidance import GuidancePydanticProgram
from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.core.query_engine import SubQuestionQueryEngine

# --- Pydantic Models ---
class CalculationInput(BaseModel):
    """Input for a single calculation."""
    function: str = Field(description="The name of the function to call (addition, subtraction, division, multiplication, percentage).")
    year: str = Field(description="The year for the financial data.")
    field1: str = Field(description="The first field name (e.g., 'Revenue', 'Debt').")
    field2: str = Field(description="The second field name. Optional for some functions.", default=None)

    def execute(self, df: pd.DataFrame) -> Union[float, str]:
        """Executes the calculation defined in the object."""
        #Dynamically creating the arguments:
        args = {}
        
        function_map = {
            "addition": add,
            "subtraction": subtract,
            "division": divide,
            "multiplication": multiply,
            "percentage": return_percentage,
        }
        func = function_map.get(self.function)
        if not func:
            return f"Error: Function {self.function} invalid"

        try: #Type validation and conversion
            val1 = extract_vals_from_df(df, self.field1, self.year)
            args[self.field1] = val1 #Uses the field name
            if self.field2:
                val2 = extract_vals_from_df(df, self.field2, self.year)
                args[self.field2] = val2 #Uses the field name
        except Exception as e:
            return f"Error retrieving data {e}"

        try:
            return func(**args)
        except TypeError as e:
            return f"Error in calculation: {e}"

class MultiCalculationRequest(BaseModel):
    """A request for multiple calculations, potentially with dependencies."""
    calculations: List[CalculationInput] = Field(description="A list of calculations to perform.")
    # could add a field for dependencies between calculations if needed.

    def execute_all(self, df: pd.DataFrame) -> List[Union[float, str]]:
        """Executes all calculations in the request."""
        results = []
        for calc in self.calculations:
            results.append(calc.execute(df))
        return results

In [63]:
from llama_index.program.openai import OpenAIPydanticProgram
from llama_index.llms.openai import OpenAI

In [ ]:
program = OpenAIPydanticProgram.from_defaults(
    output_cls=CalculationInput,
    llm=OpenAI(api_key=openai_api),
    prompt_template_str=prompt_template_str,
    allow_multiple=True,
    verbose=True,
)

# --- Main Query Function ---
def my_rag_query(query_str: str, df: pd.DataFrame) -> str:

    try:
        # Directly use GuidancePydanticProgram with the query
        output = program(query_str=query_str)  # No context needed

        if isinstance(output, CalculationInput):
            result = output.execute(df)
            return str(result)
        else:
            return "Error: Could not generate calculation input."
    except Exception as e:
        return f"An unexpected error occurred: {e}"

In [66]:
query4 = "Multiply the revenue in 2023 by the capital in 2024"
result4 = my_rag_query(query4, df)
print(f"Query 4 Result: {result4}")

Query 4 Result: An unexpected error occurred: Connection error.

In [ ]:
from llama_index.program.openai import OpenAIPydanticProgram

### Testing

In [155]:
# Test case 1: Division
json_input_1 = """
{
    "function": "division",
    "numerator": "2023",
    "denominator": "2023"
}
"""
print(f"Test 1: {execute_function(json_input_1, df)}")  # Error

# Test case 2: Addition
json_input_2 = """
{
    "function": "addition",
    "Expense": "2024",
    "Capital": "2024"
}
"""
print(f"Test 2: {execute_function(json_input_2, df)}")  # Expected: 720.0

# Test case 3: Missing data (KeyError)
json_input_3 = """
{
    "function": "addition",
    "Expense": "2023",
    "NonExistentField": "2023"
}
"""
print(f"Test 3: {execute_function(json_input_3, df)}")  # Expected: Error

# Test case 4: Invalid year
json_input_4 = """
{
 "function": "subtraction",
 "Capital": "2025",
 "Expense": "2025"

}
"""
print(f"Test 4: {execute_function(json_input_4, df)}")

#Test case 5: Invalid JSON
json_input_5 = "This is not valid JSON"
print(f"Test 5: {execute_function(json_input_5, df)}")

json_input_6 = """
{
 "function": "subtraction",
 "Capital": 2025,
 "Expense": "2025"

}
"""
print(f"Test 6: {execute_function(json_input_6, df)}")

Test 1: Error retrieving data for 'numerator' (2023): 'numerator'
Error retrieving data for 'denominator' (2023): 'denominator'
Test 2: {'Expense': 120.0, 'Capital': 600.0}
Test 3: Error retrieving data for 'NonExistentField' (2023): 'NonExistentField'
Test 4: Error retrieving data for 'Capital' (2025): '2025'
Error retrieving data for 'Expense' (2025): '2025'
Test 5: Error: Invalid JSON format.
Test 6: Error: Year for argument 'Capital' must be a string.
Error retrieving data for 'Expense' (2025): '2025'